import type { Campaign } from '../types';

/**
 * Mock campaign data for development and testing
 * Based on Trusy Instagram Marketing campaign
 */
export const mockCampaigns: Campaign[] = [
  {
    id: 'camp-1',
    name: '[JJM] Trusy | US | Instagram Marketing | Nov 2025',
    status: 'active',
    startDate: '2025-11-01',
    endDate: '2025-12-31',
    budget: 5000,
    location: 'United States',
    finalUrl: 'https://go.trusy.co/subscribe-google-new/',
    path1: 'Platform',
    path2: 'Trial',
    globalDescriptions: [
      {
        id: 'gdesc-1',
        line1: 'Transform your Instagram into a lead generation machine.',
        line2: 'Our growth specialists will help you drive 10x more reach & engagement',
      },
      {
        id: 'gdesc-2',
        line1: 'Join 35,000+ businesses using Trusy to grow their Instagram presence.',
        line2: 'Proven strategies, expert support, and powerful automation tools included',
      },
    ],
    adGroups: [
      {
        id: 'ag-1',
        campaignId: 'camp-1',
        name: 'Instagram Marketing Platform',
        status: 'active',
        maxCpc: 2.50,
        matchTypeBidding: {
          type: 'percentage',
          broad: -20,    // 20% lower than maxCpc
          phrase: 0,     // Same as maxCpc
          exact: 15,     // 15% higher than maxCpc
        },
        keywords: [
          { id: 'kw-1-1', text: 'instagram marketing platform' },
          { id: 'kw-1-2', text: 'instagram growth tool' },
          { id: 'kw-1-3', text: 'instagram automation software' },
          { id: 'kw-1-4', text: 'social media growth service' },
          { id: 'kw-1-5', text: 'instagram engagement tool' },
        ],
        ads: [
          {
            id: 'ad-1-1',
            adGroupId: 'ag-1',
            name: 'Primary Growth Platform Ad',
            status: 'enabled',
            finalUrl: 'https://go.trusy.co/subscribe-google-new/',
            path1: 'Platform',
            path2: 'Trial',
            headlines: [
              { id: 'h-1', text: '#1 Instagram Growth Platform' },
              { id: 'h-2', text: 'InstaMagnet System Included' },
              { id: 'h-3', text: '35,000+ Members Worldwide' },
              { id: 'h-4', text: 'Grow Your Instagram Fast' },
              { id: 'h-5', text: 'Expert Growth Strategies' },
              { id: 'h-6', text: '14-Day Free Trial Available' },
              { id: 'h-7', text: 'Automated Instagram Marketing' },
              { id: 'h-8', text: 'Real Results in 30 Days' },
              { id: 'h-9', text: 'Instagram Marketing Made Easy' },
              { id: 'h-10', text: 'Trusted by 35K+ Businesses' },
              { id: 'h-11', text: 'Boost Engagement & Reach' },
              { id: 'h-12', text: 'Professional Growth Tools' },
              { id: 'h-13', text: 'Start Growing Today' },
              { id: 'h-14', text: 'No Credit Card Required' },
              { id: 'h-15', text: 'Join Trusy Now' },
            ],
            descriptions: [
              { id: 'd-1', text: 'Transform your Instagram with proven growth strategies. Get expert support included.' },
              { id: 'd-2', text: 'Join 35,000+ businesses growing on Instagram. Try Trusy free for 14 days.' },
              { id: 'd-3', text: 'Automated tools + expert guidance. Everything you need to grow your Instagram.' },
              { id: 'd-4', text: 'See real results in 30 days. Powerful platform with dedicated growth specialists.' },
            ],
            createdAt: '2025-10-25T10:00:00Z',
            updatedAt: '2025-10-30T14:30:00Z',
          },
        ],
        createdAt: '2025-10-25T10:00:00Z',
        updatedAt: '2025-10-30T14:30:00Z',
      },
      {
        id: 'ag-2',
        campaignId: 'camp-1',
        name: 'Instagram Account Manager',
        status: 'active',
        maxCpc: 2.75,
        matchTypeBidding: {
          type: 'exact',
          broad: 2.00,    // Exact price for broad
          phrase: 2.75,   // Exact price for phrase (same as maxCpc)
          exact: 3.50,    // Exact price for exact match
        },
        keywords: [
          { id: 'kw-2-1', text: 'instagram account manager' },
          { id: 'kw-2-2', text: 'social media manager service' },
          { id: 'kw-2-3', text: 'instagram management service' },
          { id: 'kw-2-4', text: 'instagram marketing agency' },
          { id: 'kw-2-5', text: 'managed instagram service' },
        ],
        ads: [
          {
            id: 'ad-2-1',
            adGroupId: 'ag-2',
            name: 'Account Manager Service Ad',
            status: 'enabled',
            finalUrl: 'https://go.trusy.co/subscribe-google-new/',
            path1: 'Manager',
            path2: 'Service',
            headlines: [
              { id: 'h-2-1', text: 'Expert Instagram Managers' },
              { id: 'h-2-2', text: 'Dedicated Growth Specialist' },
              { id: 'h-2-3', text: 'Managed Instagram Service' },
              { id: 'h-2-4', text: 'White-Glove IG Management' },
              { id: 'h-2-5', text: 'Professional Account Support' },
              { id: 'h-2-6', text: 'Personal Growth Strategist' },
              { id: 'h-2-7', text: 'Done-For-You Instagram' },
              { id: 'h-2-8', text: '1-on-1 Expert Guidance' },
              { id: 'h-2-9', text: 'Instagram Manager Included' },
              { id: 'h-2-10', text: 'Proven Growth Strategies' },
              { id: 'h-2-11', text: 'Hands-Off Instagram Growth' },
              { id: 'h-2-12', text: 'Custom Growth Plan' },
              { id: 'h-2-13', text: 'Expert-Managed Accounts' },
              { id: 'h-2-14', text: 'Get Your Manager Today' },
              { id: 'h-2-15', text: 'Start Free Trial' },
            ],
            descriptions: [
              { id: 'd-2-1', text: 'Get a dedicated Instagram growth specialist. Personalized strategies for your business.' },
              { id: 'd-2-2', text: 'Professional account management included. Let experts handle your Instagram growth.' },
              { id: 'd-2-3', text: '1-on-1 support from certified growth specialists. Custom plan for your goals.' },
              { id: 'd-2-4', text: 'Hands-off Instagram management. Expert strategies + powerful automation tools.' },
            ],
            createdAt: '2025-10-25T11:00:00Z',
            updatedAt: '2025-10-30T14:30:00Z',
          },
        ],
        createdAt: '2025-10-25T11:00:00Z',
        updatedAt: '2025-10-30T14:30:00Z',
      },
      {
        id: 'ag-3',
        campaignId: 'camp-1',
        name: 'Instagram Marketing Courses',
        status: 'active',
        maxCpc: 2.25,
        keywords: [
          { id: 'kw-3-1', text: 'instagram marketing course' },
          { id: 'kw-3-2', text: 'instagram training program' },
          { id: 'kw-3-3', text: 'learn instagram marketing' },
          { id: 'kw-3-4', text: 'instagram growth course' },
          { id: 'kw-3-5', text: 'social media marketing class' },
        ],
        ads: [
          {
            id: 'ad-3-1',
            adGroupId: 'ag-3',
            name: 'Course & Training Ad',
            status: 'enabled',
            finalUrl: 'https://go.trusy.co/subscribe-google-new/',
            path1: 'Courses',
            path2: 'Training',
            headlines: [
              { id: 'h-3-1', text: 'Instagram Marketing Course' },
              { id: 'h-3-2', text: 'Learn From Growth Experts' },
              { id: 'h-3-3', text: 'Comprehensive Training Program' },
              { id: 'h-3-4', text: 'Master Instagram Growth' },
              { id: 'h-3-5', text: 'Expert-Led Video Lessons' },
              { id: 'h-3-6', text: 'Step-by-Step IG Training' },
              { id: 'h-3-7', text: 'Proven Growth Strategies' },
              { id: 'h-3-8', text: 'Access to 50+ Lessons' },
              { id: 'h-3-9', text: 'Certification Included' },
              { id: 'h-3-10', text: 'Learn at Your Own Pace' },
              { id: 'h-3-11', text: 'Complete Instagram Course' },
              { id: 'h-3-12', text: 'From Beginner to Pro' },
              { id: 'h-3-13', text: 'Lifetime Course Access' },
              { id: 'h-3-14', text: 'Start Learning Today' },
              { id: 'h-3-15', text: '14-Day Money-Back Guarantee' },
            ],
            descriptions: [
              { id: 'd-3-1', text: 'Comprehensive Instagram marketing training. Learn strategies from certified experts.' },
              { id: 'd-3-2', text: '50+ video lessons covering everything from basics to advanced tactics. Start today.' },
              { id: 'd-3-3', text: 'Master Instagram growth with expert-led courses. Certification + community included.' },
              { id: 'd-3-4', text: 'Step-by-step training program. Learn proven strategies used by 35,000+ businesses.' },
            ],
            createdAt: '2025-10-25T12:00:00Z',
            updatedAt: '2025-10-30T14:30:00Z',
          },
        ],
        createdAt: '2025-10-25T12:00:00Z',
        updatedAt: '2025-10-30T14:30:00Z',
      },
      {
        id: 'ag-4',
        campaignId: 'camp-1',
        name: 'Instagram Growth Service',
        status: 'active',
        maxCpc: 2.60,
        keywords: [
          { id: 'kw-4-1', text: 'instagram growth service' },
          { id: 'kw-4-2', text: 'grow instagram followers' },
          { id: 'kw-4-3', text: 'instagram boost service' },
          { id: 'kw-4-4', text: 'increase instagram engagement' },
          { id: 'kw-4-5', text: 'instagram reach service' },
        ],
        ads: [
          {
            id: 'ad-4-1',
            adGroupId: 'ag-4',
            name: 'Growth Service Ad',
            status: 'enabled',
            finalUrl: 'https://go.trusy.co/subscribe-google-new/',
            path1: 'Service',
            path2: 'Growth',
            headlines: [
              { id: 'h-4-1', text: 'Instagram Growth Service' },
              { id: 'h-4-2', text: '10x Your Instagram Reach' },
              { id: 'h-4-3', text: 'Real, Organic Growth' },
              { id: 'h-4-4', text: 'Boost Engagement & Reach' },
              { id: 'h-4-5', text: 'Trusted Growth Solution' },
              { id: 'h-4-6', text: 'Results in 30 Days' },
              { id: 'h-4-7', text: 'Safe & Compliant Service' },
              { id: 'h-4-8', text: 'Grow Your Following Fast' },
              { id: 'h-4-9', text: '35,000+ Happy Clients' },
              { id: 'h-4-10', text: 'Automated + Expert Help' },
              { id: 'h-4-11', text: 'Complete Growth Package' },
              { id: 'h-4-12', text: 'Instagram Marketing Experts' },
              { id: 'h-4-13', text: 'Try Free for 14 Days' },
              { id: 'h-4-14', text: 'No Long-Term Contracts' },
              { id: 'h-4-15', text: 'Get Started Now' },
            ],
            descriptions: [
              { id: 'd-4-1', text: 'Accelerate your Instagram growth with proven strategies and expert support included.' },
              { id: 'd-4-2', text: 'See real results in 30 days. Safe, compliant growth from certified specialists.' },
              { id: 'd-4-3', text: '10x your reach and engagement. Powerful tools + personalized growth strategies.' },
              { id: 'd-4-4', text: 'Join 35,000+ growing businesses. Complete Instagram growth solution with free trial.' },
            ],
            createdAt: '2025-10-25T13:00:00Z',
            updatedAt: '2025-10-30T14:30:00Z',
          },
        ],
        createdAt: '2025-10-25T13:00:00Z',
        updatedAt: '2025-10-30T14:30:00Z',
      },
      {
        id: 'ag-5',
        campaignId: 'camp-1',
        name: 'Instagram Automation Tools',
        status: 'active',
        maxCpc: 2.40,
        matchTypeBidding: {
          type: 'percentage',
          broad: -15,
          phrase: 0,
          exact: 10,
        },
        keywords: [
          { id: 'kw-5-1', text: 'instagram automation tool' },
          { id: 'kw-5-2', text: 'instagram scheduler' },
          { id: 'kw-5-3', text: 'instagram posting automation' },
          { id: 'kw-5-4', text: 'instagram management software' },
          { id: 'kw-5-5', text: 'automate instagram posts' },
        ],
        ads: [
          {
            id: 'ad-5-1',
            adGroupId: 'ag-5',
            name: 'Automation Tools Ad',
            status: 'enabled',
            finalUrl: 'https://go.trusy.co/subscribe-google-new/',
            path1: 'Tools',
            path2: 'Automation',
            headlines: [
              { id: 'h-5-1', text: 'Instagram Automation Tools' },
              { id: 'h-5-2', text: 'Smart Instagram Scheduler' },
              { id: 'h-5-3', text: 'Automate Your Instagram' },
              { id: 'h-5-4', text: 'All-in-One IG Platform' },
              { id: 'h-5-5', text: 'Save 10+ Hours Per Week' },
              { id: 'h-5-6', text: 'Advanced Automation Suite' },
              { id: 'h-5-7', text: 'Schedule, Post & Analyze' },
              { id: 'h-5-8', text: 'Instagram Made Effortless' },
              { id: 'h-5-9', text: 'Powerful Management Tools' },
              { id: 'h-5-10', text: 'Complete IG Toolkit' },
              { id: 'h-5-11', text: 'Streamline Your Workflow' },
              { id: 'h-5-12', text: 'Professional IG Software' },
              { id: 'h-5-13', text: 'Try All Features Free' },
              { id: 'h-5-14', text: 'No Technical Skills Needed' },
              { id: 'h-5-15', text: 'Start Free Trial Today' },
            ],
            descriptions: [
              { id: 'd-5-1', text: 'Powerful Instagram automation tools. Save time while growing your presence faster.' },
              { id: 'd-5-2', text: 'Schedule posts, analyze performance, and automate engagement. All-in-one platform.' },
              { id: 'd-5-3', text: 'Professional Instagram management made easy. Advanced tools + expert support included.' },
              { id: 'd-5-4', text: 'Save 10+ hours per week with smart automation. Everything you need in one platform.' },
            ],
            createdAt: '2025-10-25T14:00:00Z',
            updatedAt: '2025-10-30T14:30:00Z',
          },
        ],
        createdAt: '2025-10-25T14:00:00Z',
        updatedAt: '2025-10-30T14:30:00Z',
      },
    ],
    createdAt: '2025-10-25T10:00:00Z',
    updatedAt: '2025-10-30T14:30:00Z',
  },
];

export default mockCampaigns;
